import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import WhatsAppFloat from "../components/Whatsapp/Whatsapp.jsx";
import NotificationBell from "@/components/notifications/NotificationBell";
import LanguageToggle from "@/components/LanguageToggle";
import Script from "next/script";




/* Existing fonts (KEEP) */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Army Industeries",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          font-sans
          antialiased
          bg-gray-50
        `}
      >
       

        {/* 🔹 Language Switch (Top Right Corner) */}
        <div style={{ position: "fixed", top: 10, right: 20, zIndex: 9999 }}>
          {/* <LanguageToggle /> */}
<div id="google_translate_element" style={{ display: "none" }}></div>

        </div>

        <Toaster position="top-right" toastOptions={{ duration: 4000 }} />
        {children}
        <WhatsAppFloat />

        {/* 🔹 Google Translate Script */}
        <Script id="google-translate-init" strategy="afterInteractive">
  {`
    function googleTranslateElementInit() {
      new google.translate.TranslateElement(
        {
          pageLanguage: 'en',
          includedLanguages: 'en,hi',
          autoDisplay: false
        },
        'google_translate_element'
      );
    }
  `}
</Script>

<Script
  src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
  strategy="afterInteractive"
/>
      </body>
    </html>
  );
}

