import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import WhatsAppFloat from "../components/Whatsapp/Whatsapp.jsx";
import NotificationBell from "@/components/notifications/NotificationBell";

/* Existing fonts (KEEP) */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Army Industry",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          font-sans
          antialiased
          bg-gray-50
        `}
      >
        <Toaster position="top-right" toastOptions={{ duration: 4000 }} />
        {children}
        <WhatsAppFloat />
      </body>
    </html>
  );
}
